[2021-12-04 10:30:46 +0800] [23759] [INFO] Starting gunicorn 20.1.0
[2021-12-04 10:30:46 +0800] [23759] [INFO] Listening at: http://127.0.0.1:6868 (23759)
[2021-12-04 10:30:46 +0800] [23759] [INFO] Using worker: gevent
[2021-12-04 10:30:46 +0800] [23765] [INFO] Booting worker with pid: 23765
[2021-12-04 10:30:46 +0800] [23766] [INFO] Booting worker with pid: 23766
[2021-12-04 10:30:46 +0800] [23767] [INFO] Booting worker with pid: 23767
[2021-12-04 10:30:46 +0800] [23768] [INFO] Booting worker with pid: 23768
[2021-12-04 10:30:46 +0800] [23769] [INFO] Booting worker with pid: 23769
[2021-12-04 10:30:46 +0800] [23770] [INFO] Booting worker with pid: 23770
[2021-12-04 10:30:46 +0800] [23771] [INFO] Booting worker with pid: 23771
[2021-12-04 10:30:46 +0800] [23772] [INFO] Booting worker with pid: 23772
[2021-12-04 10:30:46 +0800] [23773] [INFO] Booting worker with pid: 23773
[2021-12-04 10:30:50 +0800] [23759] [INFO] Handling signal: int
[2021-12-04 10:30:50 +0800] [23766] [INFO] Worker exiting (pid: 23766)
[2021-12-04 10:30:50 +0800] [23769] [INFO] Worker exiting (pid: 23769)
[2021-12-04 10:30:50 +0800] [23772] [INFO] Worker exiting (pid: 23772)
[2021-12-04 10:30:50 +0800] [23770] [INFO] Worker exiting (pid: 23770)
[2021-12-04 10:30:50 +0800] [23768] [INFO] Worker exiting (pid: 23768)
[2021-12-04 10:30:50 +0800] [23765] [INFO] Worker exiting (pid: 23765)
[2021-12-04 10:30:50 +0800] [23767] [INFO] Worker exiting (pid: 23767)
[2021-12-04 10:30:50 +0800] [23773] [INFO] Worker exiting (pid: 23773)
[2021-12-04 10:30:50 +0800] [23771] [INFO] Worker exiting (pid: 23771)
[2021-12-04 10:30:52 +0800] [23759] [INFO] Shutting down: Master
[2021-12-04 10:31:38 +0800] [23829] [INFO] Starting gunicorn 20.1.0
[2021-12-04 10:31:38 +0800] [23829] [INFO] Listening at: http://127.0.0.1:6868 (23829)
[2021-12-04 10:31:38 +0800] [23829] [INFO] Using worker: gevent
[2021-12-04 10:31:38 +0800] [23837] [INFO] Booting worker with pid: 23837
[2021-12-04 10:31:38 +0800] [23839] [INFO] Booting worker with pid: 23839
[2021-12-04 10:31:38 +0800] [23840] [INFO] Booting worker with pid: 23840
[2021-12-04 10:31:38 +0800] [23841] [INFO] Booting worker with pid: 23841
[2021-12-04 10:31:38 +0800] [23842] [INFO] Booting worker with pid: 23842
[2021-12-04 10:31:38 +0800] [23837] [INFO] Worker exiting (pid: 23837)
[2021-12-04 10:31:38 +0800] [23840] [INFO] Worker exiting (pid: 23840)
[2021-12-04 10:31:38 +0800] [23839] [INFO] Worker exiting (pid: 23839)
[2021-12-04 10:31:39 +0800] [23841] [INFO] Worker exiting (pid: 23841)
[2021-12-04 10:31:39 +0800] [23844] [INFO] Booting worker with pid: 23844
[2021-12-04 10:31:39 +0800] [23845] [INFO] Booting worker with pid: 23845
[2021-12-04 10:31:39 +0800] [23846] [INFO] Booting worker with pid: 23846
[2021-12-04 10:31:39 +0800] [23847] [INFO] Booting worker with pid: 23847
[2021-12-04 10:31:39 +0800] [23829] [INFO] Handling signal: int
[2021-12-04 10:31:45 +0800] [23845] [INFO] Worker exiting (pid: 23845)
[2021-12-04 10:31:45 +0800] [23846] [INFO] Worker exiting (pid: 23846)
[2021-12-04 10:31:45 +0800] [23847] [INFO] Worker exiting (pid: 23847)
[2021-12-04 10:31:45 +0800] [23844] [INFO] Worker exiting (pid: 23844)
[2021-12-04 10:31:45 +0800] [23842] [INFO] Worker exiting (pid: 23842)
[2021-12-04 10:31:45 +0800] [23829] [WARNING] Worker with pid 23847 was terminated due to signal 2
[2021-12-04 10:31:45 +0800] [23829] [WARNING] Worker with pid 23846 was terminated due to signal 2
[2021-12-04 10:31:45 +0800] [23829] [WARNING] Worker with pid 23842 was terminated due to signal 2
[2021-12-04 10:31:45 +0800] [23829] [WARNING] Worker with pid 23845 was terminated due to signal 2
[2021-12-04 10:31:45 +0800] [23829] [WARNING] Worker with pid 23844 was terminated due to signal 2
[2021-12-04 10:31:45 +0800] [23829] [INFO] Shutting down: Master
[2021-12-04 10:31:55 +0800] [23895] [INFO] Starting gunicorn 20.1.0
[2021-12-04 10:31:55 +0800] [23895] [INFO] Listening at: http://127.0.0.1:6868 (23895)
[2021-12-04 10:31:55 +0800] [23895] [INFO] Using worker: gevent
[2021-12-04 10:31:55 +0800] [23908] [INFO] Booting worker with pid: 23908
[2021-12-04 10:31:55 +0800] [23909] [INFO] Booting worker with pid: 23909
[2021-12-04 10:31:55 +0800] [23911] [INFO] Booting worker with pid: 23911
[2021-12-04 10:31:55 +0800] [23912] [INFO] Booting worker with pid: 23912
[2021-12-04 10:31:55 +0800] [23913] [INFO] Booting worker with pid: 23913
[2021-12-04 10:31:55 +0800] [23914] [INFO] Booting worker with pid: 23914
[2021-12-04 10:31:55 +0800] [23915] [INFO] Booting worker with pid: 23915
[2021-12-04 10:31:55 +0800] [23916] [INFO] Booting worker with pid: 23916
[2021-12-04 10:31:55 +0800] [23917] [INFO] Booting worker with pid: 23917
[2021-12-04 10:36:45 +0800] [23895] [INFO] Handling signal: int
[2021-12-04 10:36:45 +0800] [23909] [INFO] Worker exiting (pid: 23909)
[2021-12-04 10:36:45 +0800] [23916] [INFO] Worker exiting (pid: 23916)
[2021-12-04 10:36:45 +0800] [23913] [INFO] Worker exiting (pid: 23913)
[2021-12-04 10:36:45 +0800] [23908] [INFO] Worker exiting (pid: 23908)
[2021-12-04 10:36:45 +0800] [23912] [INFO] Worker exiting (pid: 23912)
[2021-12-04 10:36:45 +0800] [23914] [INFO] Worker exiting (pid: 23914)
[2021-12-04 10:36:45 +0800] [23917] [INFO] Worker exiting (pid: 23917)
[2021-12-04 10:36:45 +0800] [23911] [INFO] Worker exiting (pid: 23911)
[2021-12-04 10:36:45 +0800] [23915] [INFO] Worker exiting (pid: 23915)
[2021-12-04 10:36:48 +0800] [23895] [INFO] Shutting down: Master
[2021-12-04 10:53:00 +0800] [25589] [INFO] Starting gunicorn 20.1.0
[2021-12-04 10:53:00 +0800] [25589] [INFO] Listening at: http://127.0.0.1:6868 (25589)
[2021-12-04 10:53:00 +0800] [25589] [INFO] Using worker: gevent
[2021-12-04 10:53:01 +0800] [25596] [INFO] Booting worker with pid: 25596
[2021-12-04 10:53:01 +0800] [25597] [INFO] Booting worker with pid: 25597
[2021-12-04 10:53:01 +0800] [25598] [INFO] Booting worker with pid: 25598
[2021-12-04 10:53:01 +0800] [25599] [INFO] Booting worker with pid: 25599
[2021-12-04 10:53:01 +0800] [25600] [INFO] Booting worker with pid: 25600
[2021-12-04 10:53:01 +0800] [25602] [INFO] Booting worker with pid: 25602
[2021-12-04 10:53:01 +0800] [25603] [INFO] Booting worker with pid: 25603
[2021-12-04 10:53:01 +0800] [25606] [INFO] Booting worker with pid: 25606
[2021-12-04 10:53:01 +0800] [25607] [INFO] Booting worker with pid: 25607
[2021-12-04 10:53:47,869] ERROR in app: Exception on /api/backend/menu [GET]
Traceback (most recent call last):
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/pymysql/connections.py", line 614, in connect
    (self.host, self.port), self.connect_timeout, **kwargs
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/gevent/socket.py", line 101, in create_connection
    sock.connect(sa)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/gevent/_socketcommon.py", line 613, in connect
    self._wait(self._write_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '10.1.0.15' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kuainiu/PycharmProjects/auto-test/app/api/web/__init__.py", line 23, in get_menu
    menu_list = Menu.query.filter(Menu.menu_parent_id == 0).order_by(Menu.menu_order).all()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2699, in all
    return self._iter().all()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2837, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1683, in execute
    conn = self._connection_for_bind(bind, close_with_result=True)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1535, in _connection_for_bind
    conn = engine.connect(**kw)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3165, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3244, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect
    e, dialect, self
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2069, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3211, in _wrap_pool_connect
    return fn()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/Users/kuainiu/PycharmProjects/auto-test/venv/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '10.1.0.15' (timed out)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-12-04 10:54:52 +0800] [25589] [INFO] Handling signal: int
[2021-12-04 10:54:52 +0800] [25599] [INFO] Worker exiting (pid: 25599)
[2021-12-04 10:54:52 +0800] [25600] [INFO] Worker exiting (pid: 25600)
[2021-12-04 10:54:52 +0800] [25607] [INFO] Worker exiting (pid: 25607)
[2021-12-04 10:54:52 +0800] [25596] [INFO] Worker exiting (pid: 25596)
[2021-12-04 10:54:52 +0800] [25603] [INFO] Worker exiting (pid: 25603)
[2021-12-04 10:54:52 +0800] [25606] [INFO] Worker exiting (pid: 25606)
[2021-12-04 10:54:52 +0800] [25598] [INFO] Worker exiting (pid: 25598)
[2021-12-04 10:54:52 +0800] [25597] [INFO] Worker exiting (pid: 25597)
[2021-12-04 10:54:52 +0800] [25602] [INFO] Worker exiting (pid: 25602)
[2021-12-04 10:54:54 +0800] [25589] [INFO] Shutting down: Master
